name: "Lian Lian"
description: "Lian Lian"

url: "http://lianliansite.com"


collections:
- techmemo

collections:
  techmemo:
    output: true
    permalink: /techmemo/:path/

gems:
  - jekyll-sitemap